version: 2.1

commands:
  cardcase_setup:
    description: "Get the app ready to test"
    steps:
      - checkout
      - run:
          name: Setup secret files
          command: |
            echo ${LOCAL_PROPERTIES} > ~/code/local.properties
            echo ${FABRIC_PROPERTIES} > ~/code/app/fabric.properties
            echo ${GOOGLE_ANALYTICS_TRACKER_XML} > ~/code/app/src/main/res/xml/google_analytics_tracker.xml
            echo ${GOOGLE_SERVICES_JSON} > ~/code/app/google-services.json
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

executors:
  cardcase_executor:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx3200m

jobs:
  build:
    executor: cardcase_executor
    steps:
      - cardcase_setup
      - run:
          name: Build
          command: ./gradlew assemble
  lint:
    executor: cardcase_executor
    steps:
      - cardcase_setup
      - run:
          name: Run Lint
          command: ./gradlew lint
      - store_artifacts:
          path: app/build/reports
          destination: reports
  test:
    executor: cardcase_executor
    steps:
      - cardcase_setup
      - run:
          name: Run Tests
          command: ./gradlew test
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/reports
          destination: reports

workflows:
  version: 2.1
  build_lint_test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build